
"""Add watermark hash storage to images"""

from alembic import op
import sqlalchemy as sa

revision = "4958a8849531"
down_revision = "51a43ca688a3"
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('watermark_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'watermark_hash')
    # ### end Alembic commands ###
