
"""Add allow_scientific_use flag to images"""

from alembic import op
import sqlalchemy as sa

revision = "51a43ca688a3"
down_revision = "c49753e7510e"
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "allow_scientific_use",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.alter_column(
        "images",
        "allow_scientific_use",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'allow_scientific_use')
    # ### end Alembic commands ###
