
"""Add observing condition ratings to images"""

from alembic import op
import sqlalchemy as sa

revision = "79a3407b3852"
down_revision = "4958a8849531"
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('seeing_rating', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('transparency_rating', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('bortle_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'bortle_rating')
    op.drop_column('images', 'transparency_rating')
    op.drop_column('images', 'seeing_rating')
    # ### end Alembic commands ###
