
"""Add observatory and derotation metadata columns"""

from alembic import op
import sqlalchemy as sa

revision = "c49753e7510e"
down_revision = "0001_initial"
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('derotation_time', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('observatory_name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('observatory_location', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('observatory_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('observatory_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'observatory_longitude')
    op.drop_column('users', 'observatory_latitude')
    op.drop_column('users', 'observatory_location')
    op.drop_column('users', 'observatory_name')
    op.drop_column('images', 'derotation_time')
    # ### end Alembic commands ###
